### PR TITLE
docs: rename layer0 to Edgio

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
Do not merge before: https://github.com/unjs/nitro/pull/822

### ❓ Type of change

- [X] 📖 Documentation (updates to the documentation or readme)

### CODE REVIEW

**Comment by rishi-raj-jain** [comment]
@manniL

Is there a way I can add an icon for Edgio like it's for others? I tried finding it but couldn't see where are the icons being loaded from.

**Comment by manniL** [comment]
@rishi-raj-jain Sadly I don't know. But probably @clemcode can help you here 😋

**Comment by rishi-raj-jain** [comment]
@manniL Thanks for the ref, @clemcode can you have a look and let me know?

**Comment by rishi-raj-jain** [comment]
@manniL @danielroe Would you have an idea about where I can edit the icon?

**Comment by danielroe** [comment]
I believe we're using iconify - so https://github.com/gilbarbara/logos.

**Comment by rishi-raj-jain** [comment]
@danielroe 

Thanks to @pi0's activeness that now this is completed via https://github.com/unjs/nitro/pull/858! 💚

**Comment by danielroe** [comment]
Fantastic! Just let me know when we're good to go here.

**Comment by rishi-raj-jain** [comment]
@danielroe 

I think we are just left with https://github.com/gilbarbara/logos/issues/571 for which I can do another PR once that gets in, makes sense?

**Review by danielroe — APPROVED** [review]

**Pull request merged**
