### PR TITLE
fix(nuxt): pass params to client-only slot

### LINKED ISSUE #6581: Usage of slots in client-only components throwing errors in production
### Environment

Nuxt CLI v3.0.0-rc.8
RootDir: /Users/samh/wow
Nuxt project info: 

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/ffxsam/repro-nuxt3-broken-slots

1. `yarn build`
2. `yarn preview`

### Describe the bug

Using slots in client-only components throws an error in production only:

```
TypeError: Cannot read properties of undefined (reading 'test')
```

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by huang-julien**
### 🔗 Linked issue

resolve  #6581

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

#6581 Boom.client component compilation: [SFC playground](https://sfc.vuejs.org/#eNp9kTFvgzAQhf/KyRORALdDF0So2r1Kh45eKBwJkbEtnyED4r/3HECKWqmbfe/8Pd+7Wbw5l08jikKU1PjeBSAMowNdm/NRiUBKVMr0g7M+wOyxS6HFrjf46a2jBTpvB1CCEUooA6BMYw0FcFGG42NzOV9Qa/taAAXfm/NSJYe9Xdu65RI/YIsk+BFZYt8OEiY1SJQ3ukcTDjBHG/7kVz+gHUOSHOBYrVXYOflU6xGZ1tWaMEpLCs8vT09MXSK4lOu0PBtfAg5O1wH5BlC2/VS9n04fMK8fXpZSxtouwpTRxd44nc3tHlF0L0nbAKYeMEaHFJQAub7bCKV88BKpWIPNhtrlV7KG13AfRG0Cp1/so20hF3y4hOCokJK6Ji7vSrn1Z8mn3I8mcC450pB9e3sj9AxWIn1gSC5O6DOPpkWP/j/mr9Y/3Hu0nKlYfgBTY8qd) (See SSR part line 33)

In https://github.com/nuxt/framework/pull/6165 the params of the setupState (when it is a function) were ignored. 
https://github.com/nuxt/framework/blob/2ec2d9b484b9b72a193e1678123c3cce6a454b62/packages/nuxt/src/app/components/client-only.mjs#L47-L50

This PR make the setupState render function reproduce the same behavior when overriding the render option of the component here: 
https://github.com/nuxt/framework/blob/2ec2d9b484b9b72a193e1678123c3cce6a454b62/packages/nuxt/src/app/components/client-only.mjs#L23-L29

You can test this here https://github.com/huang-julien/nuxt-3/tree/test/client-slot-fix

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by danielroe** [comment]
You are quick!

**Review by danielroe — APPROVED** [review]

**Comment by huang-julien** [comment]
@danielroe thank you!  :+1:

**Comment by pi0** [comment]
Thanks for the quick fix! I'm wondering if we could add a test page to basic fixture to ensure this behavior keeps working.

**Comment by huang-julien** [comment]
> Thanks for the quick fix! I'm wondering if we could add a test page to basic fixture to ensure this behavior keeps working.

yes i think so, i can do it if you want (monday). I'm not sure about this but does nuxt test utils compile the SFCs to simulate a behavior in prod ?

2 different SFC needs to be tested:
- [ ] SFC with a setup script (attrs, props ...)
- [ ] SFC without setup script exporting an object (attrs, props ...)

**Comment by pi0** [comment]
> does nuxt test utils compile the SFCs to simulate a behavior in prod ?

Yes. [test fixture](https://github.com/nuxt/framework/tree/main/test/fixtures/basic) is being compiled and built before running tests. We can have a dedicated page for test suite.

**Comment by huang-julien** [comment]
@pi0 I might have an issue with the tests. The `ClientOnlySetupScript.client.vue` component in `test/fixtures/basic` has a different behavior in tests compared to the built env. The attributes are not being rendered to the html. I could'nt reproduce this issue by building the playground. Even if there's no more errors, the HTML rendered is different in build/prod vs test. I'll leave this as draft for now

**Pull request merged**
