### PR TITLE
feat(nuxi): warn on standalone nitro config in dev

### PR DESCRIPTION
**Pull request by manniL**
### 🔗 Linked issue

resolves https://github.com/nuxt/framework/issues/7965

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

When running `nuxi dev` and using a standalone `nitro.config.ts` (or `.js`), warn the user about it.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by danielroe — APPROVED** [review]
Good idea.

**Comment by darthf1** [comment]
Would this be the same for `vitest.config.ts` vs the `vite.test` config key in `nuxt.config.ts`?

**Comment by danielroe** [comment]
Good question. What do you think @antfu?

**Comment by antfu** [comment]
I am not very sure about it. It feels a little bit over-babysitting to me, as:

1. Extra performance cost, especially if later we need to support `{webpack,vite,vitest}.config.{js,ts,mjs,cjs,mts,cts}` etc.
2. In some cases users might configure those configs for other usages, like using Nuxt and Nitro in two different build steps
3. In some cases users might use standalone configs for better IDE support, and import dynamically, like:

```ts
import nitroConfig from './nitro.config'
import viteConfig from './vite.config'

export default defineNuxtConfig({
  nitro: nitroConfig,
  vite: viteConfig
})
```

Then this warning could be false-alarmed.

**Comment by manniL** [comment]
@antfu 

Very valid points! On the other hand, I see quite some users who use an additional `nitro.config` to their `nuxt.config` not knowing that they should not. 


Should we improve documentation then instead regarding these?

**Comment by pi0** [comment]
Thanks for the PR @manniL. As @antfu mentioned, it might get tricky for cases that `nitro.config` is also present for another project or user's preferred convention to specify it (while not recommending this some might find it useful). 

In order to be consistent with other sub-packages such as vite that we ignore their config but don't warn, current behavior seems fine.

**Comment by pi0** [comment]
> Should we improve documentation then instead regarding these?

Yes specially on nitro docs we can make it better for Nuxt users.

**Comment by manniL** [comment]
Should we close #7965 then?

**Pull request closed without merging**
