### PR TITLE
feat(nuxt)!: support universal global middleware

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/framework/issues/4752, closes https://github.com/nuxt/framework/pull/4795

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This adds support for global middleware in the universal router - ie. even if the user doesn't have a `pages/` directory. Note that only _global_ middleware is supported so middleware must have a `.global.ts` suffix for it to be applied on route navigation. (This is for consistency.)

### 👉 Migration

* If you are using `pages:middleware:extend` hook, then you can switch to using `app:resolve`, where you will be able to access `app.middleware`.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Atinux** [comment]
Looks good to me ❤️ , would be nice to add a test for.

**Comment by pi0** [comment]
As discussed with @danielroe remaining changes:

- Use an array format for middleware (supporting nameless middleware and consistency)
- Add an alternative hook to extend middleware.

**Comment by danielroe** [comment]
@pi0 Let me know when you plan to review this and I will resolve conflicts.

**Comment by pi0** [comment]
@danielroe You can rebase. I think we are close to merge :)

**Review by pi0 — APPROVED** [review]

**Pull request merged**
