### PR TITLE
docs: add minimum sitemap to nuxt.com

### PR DESCRIPTION
**Pull request by IsraelOrtuno**
### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

I have added a very basic sitemap file for SEO purposes. This could be improved in the future by adding other parameters such as `priority` and `lastmod` if there's a way to guess when a `content/**/.md` file was modified.

Also included the sitemap in the robots.txt as search engines suggest so they can easily find it.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Atinux** [comment]
Thank you so much @IsraelOrtuno ❤️ 

I think the server code had to move to the nuxt-website-theme repo (we plan to open source in the next weeks), cc @clemcode

**Comment by IsraelOrtuno** [comment]
Was looking for it for a while to see where it would make more sense but since I did not find it I thought adding it here

**Comment by Atinux** [comment]
It was great to add it here, would be easy for us to move into the theme (beauty of nuxt extends)

**Comment by clemcode** [comment]
@IsraelOrtuno the code has been moved to the theme repository, and will be up tomorrow. Thanks a lot for the contribution, I will now close the PR.

**Pull request closed without merging**
