### PR TITLE
feat(pages)!: explicitly allow optional params with `[[`

### PR DESCRIPTION
**Pull request by danielroe**
Resolves https://github.com/nuxt/framework/issues/3352. Also see https://github.com/nuxt/framework/issues/4520.

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Currently routes _ending_ in a dynamic param are marked as optional, e.g.: `~/pages/[slug].vue`.

This PR instead requires double bracket syntax to enable optional params: e.g. `~/pages/[[slug]].vue`. (This also means you can enable optional parameters earlier in the path.)

### 👉 Migration

If you are relying on `[slug]` at the end of a route to generate an optional parameter, you will need to rewrite it as `[[slug]]`.

### CODE REVIEW

**Comment by danielroe** [comment]
@pi0 How about we change the default to non-optional at end of route, and use double brackets - e.g. `[[slug]]` - to indicate optionality, which can apply to any level in path?

**Comment by pi0** [comment]
Double bracket seems a nice idea!

**Comment by Atinux** [comment]
I love this idea!

**Comment by Atinux** [comment]
Happy to merge once the documentation is updated. Any blocked @pi0 ?

**Review by pi0 — APPROVED** [review]

**Pull request merged**
