### PR TITLE
fix(nuxt3): allows plugins without default export

### PR DESCRIPTION
**Pull request by antfu**
### 🔗 Linked issue

https://github.com/antfu/unocss/issues/27

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

For example, in some cases, we might be relying on module side-effect in a plugin but does not have the explicit `default export`, this PR mocked those plugins to provide a noop function to avoid the undefined error.

```ts
// plugins/foo.js
import 'winid.css'
```

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by danielroe — COMMENTED** [review]
Should we instead change so we are not importing default at all?

https://github.com/nuxt/framework/blob/07086c839753f349d6b250bb80d5161b2bbb5d56/packages/nuxt3/src/core/templates.ts#L33-L44

so rather than:
```js
import asd_234 from '/my/no/default.js'

export default [
  asd_234
]
```
We get:

```js
import '/my/no/default.js'

export default []
```

**Comment by antfu** [comment]
That's a good point, I guess we could use `mlly` to detect if it has `default export` right? But then my concern become that some plugins might not be on the disk by served by some virtual modules and we might not always been able to read their content?

**Comment by pi0** [comment]
> That's a good point, I guess we could use mlly to detect if it has default export right? But then my concern become that some plugins might not be on the disk by served by some virtual modules and we might not always been able to read their content?

I love this idea this can help reducing runtime check overheads + removing workaround we had for bridge default export ! Well actually mlly can detect syntax from any string content (also from vfs)

**Review by pi0 — APPROVED** [review]
Side note: You still need to add a default export `export default {}` to the plugin with this fix. Vite throws an error otherwise since we generate `import x from 'plugin'` in template

**Pull request merged**
