### PR TITLE
feat(nuxt): add `setLayout` utility

### PR DESCRIPTION
**Pull request by 516310460**
### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by 516310460** [comment]
Add `useLayout` composables. can change `layout`
Within your pages, components, and plugins you can use useLayout to get access to data that resolves asynchronously.

Added document and composables

https://github.com/nuxt/framework/issues/6824

**Comment by 516310460** [comment]
Extend it: https://v3.nuxtjs.org/guide/directory-structure/layouts/#overriding-a-layout-on-a-per-page-basis

**Comment by pi0** [comment]
Thanks for PR. I personally like it if renamed to `setLayout`. @danielroe What do you think about such utility?

**Comment by 516310460** [comment]
> Thanks for PR. I personally like it if renamed to `setLayout`. @danielroe What do you think about such utility?

Currently, it can. Maybe it will have more missions in the future

**Review by danielroe — COMMENTED** [review]
I agree, we don't want to have `useLayout(layoutName: string)` as the API. (If we used `useLayout` we would want it to return a ref to the layout, I think.)

`setLayout` does make sense, and I think preserves the opportunity to add more helpers if needed. We would need to document that this will work on the client, or (if on server) must be used within nuxt route middleware, and, moreover, persisted via a `useState` so that the client can ensure that the layout it renders is the same.

Possibly we could also implement this workflow - when !nuxtApp.isHydrating? - within this PR.

**Comment by 516310460** [comment]
Yes. Named `setLayout` is consistent with `nuxt2`, someone may want to judge and set `layout` in `middleware`

**Comment by danielroe** [comment]
@516310460 FYI, I'll be looking at this shortly to see if it's possible to [implement my comment above](https://github.com/nuxt/framework/pull/6826#pullrequestreview-1080801174) in this PR.

**Comment by 516310460** [comment]
> @516310460 FYI, I'll be looking at this shortly to see if it's possible to [implement my comment above](https://github.com/nuxt/framework/pull/6826#pullrequestreview-1080801174) in this PR.

Yes, I updated the source code to automatically trigger this PR

**Comment by danielroe** [comment]
Is there a reason you closed this?

**Comment by 516310460** [comment]
> Is there a reason you closed this?



> 

I need to submit first :)
Link: https://github.com/nuxt/framework/pull/6870

**Comment by danielroe** [comment]
Oh, I see. You can also use multiple branches in your fork for different PRs. (Might be easier.)

**Comment by 516310460** [comment]
> Oh, I see. You can also use multiple branches in your fork for different PRs. (Might be easier.)

Thanks, I've never done this before, I'll try this in the future

**Comment by 516310460** [comment]
Can you help me check my code

https://github.com/nuxt/framework/pull/6870

**Comment by danielroe** [comment]
You're doing a great job :)

**Comment by 516310460** [comment]
> You're doing a great job :)

Start testing and prepare documents

**Comment by 516310460** [comment]
I added usage in `examples/routing/layouts`, do I need to add `setLayout` documentation in `/api/composables/*` or `guide/directory-structure/layouts`?

**Comment by 516310460** [comment]
Persist using `useState`, available in `middleware`

**Comment by 516310460** [comment]
Please check

**Comment by 516310460** [comment]
@danielroe Thanks you. source context

**Comment by danielroe** [comment]
My to-do list before merging:

- [ ] rename to `setPageLayout` to make it clearer how this composable operates (wdyt  @pi0?)
- [ ] update more docs to refer to this composable
- [ ] fix behaviour in plugins to use router hook as well

**Comment by pi0** [comment]
Makes sense to call it `setPageLayout` and also improve plugin behavior. I think we can make `_layout` a permanent state as well using a pages module plugin instead of `setState`.

@516310460 Since this PR is made from your `main` branch I think we could move it to a Nuxt branch and continue updating it. Thanks for the idea and initial works ❤️ 

@danielroe Do you mind if I move forward with branch creation to merge and letting you opening new PR from branch once could?

**Comment by pi0** [comment]
@516310460 Also do you have a discord account? I would like to talk with you with daniel and helping on contribution process together.

**Comment by 516310460** [comment]
> @516310460 Also do you have a discord account? I would like to talk with you with daniel and helping on contribution process together.

I have an account number

**Comment by pi0** [comment]
Perfect. Mind to send a DM to me? pi0#6582

**Comment by danielroe** [comment]
@pi0 Thanks, yes please!

**Comment by 516310460** [comment]
> Perfect. Mind to send a DM to me? pi0#6582

good Please wait a moment. I was having dinner

**Comment by 516310460** [comment]
@pi0 I have already DM you

**Comment by pi0** [comment]
~> https://github.com/nuxt/framework/issues/6977

**Pull request merged**
