### PR TITLE
feat(nuxt): filter support for `clearNuxtData`

### PR DESCRIPTION
**Pull request by cawa-93**
### 🔗 Linked issue

Continuation of  https://github.com/nuxt/framework/pull/5227

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Uncovered use case: 
Remove cache for several unknown keys. Example: you have app with posts and filter for posts. Each query for posts saved in cache in uniq key, like `posts.list-{param1:1}`, `posts.list-{param2:2}`, `posts.list-{param1:1,param2:3}` (nuxt-trpc works llike that). In this case you may want clear data for all keys `posts.list-*`. 
May be `clearNuxtData` should also accept function to filter keys?
```ts
clearNuxtData(key => key.startsWith('posts.list'))
```
Or provide another method to get all keys in cache and filter it manually:
```ts
clearNuxtData(
  getNuxtDataKeys().filter(key => key.startsWith('posts.list'))
)
```

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Atinux** [comment]
I do like the idea of a filter method ☺️

**Comment by Atinux** [comment]
Wondering if this could be applied also to refreshNuxtData(): https://v3.nuxtjs.org/api/utils/refresh-nuxt-data

**Comment by cawa-93** [comment]
I tried, but `refreshNuxtData` doesn't have keys for filtering

https://github.com/cawa-93/framework/blob/ba4828c1dcb4ef7b24e3a3cb0294b754c4f2b811/packages/nuxt/src/app/composables/asyncData.ts#L249-L255

**Comment by pi0** [comment]
LGTM. Supporting for `refreshNuxtData` is also good idea. We can implement similar for fallback when no keys are set.

**Pull request merged**
