### PR TITLE
feat(nuxt): support prefetching `<nuxt-link>`

### PR DESCRIPTION
**Pull request by Mini-ghost**
### 🔗 Linked issue

#3649 #2086

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Support `prefetch` prop for `<nuxt-link>`. This implementation is refer to https://github.com/nuxt/framework/discussions/2086#discussioncomment-1683819. Need a polyfill for `requestIdleCallback` ?

Also, I'm not sure how to use Link Prefetching like below, because `path` are unpredictable.

```html 
<link rel="prefetch" as="script" href="path" />
````

The implementation of this PR refers to nuxt2, maybe we can generate a router manifest. and mapping file path when triggering prefetch  ? 

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Mini-ghost** [comment]
@pi0 @Atinux I will add polyfill for `requestIdleCallback`. And I think we have two opportunities to add polyfill

1. Add polyfill at file start and run in client side.

```ts
const requestIdleCallback = process.client
  ? window.requestIdleCallback || function (cb) {
    const start = Date.now()
    const idleDeadline = {
      didTimeout: false,
      timeRemaining () {
        return Math.max(0, 50 - (Date.now() - start))
      }
    }
    return window.setTimeout(function () {
      cb(idleDeadline)
    }, 1)
  }
  : (() => {}) as any as Window['requestIdleCallback']
 ```

2. When component mounted and need prefetch, implement with Singleton.

```ts
let requestIdleCallback: Window['requestIdleCallback'] | null = null
```

```ts
onMounted(() => {
  if (!shouldPrefetch.value) { return }

  // add `requestIdleCallback` polyfill if not support and need prefetch
  if (!requestIdleCallback) {
    requestIdleCallback = window.requestIdleCallback || function (cb) {
      const start = Date.now()
      const idleDeadline = {
        didTimeout: false,
        timeRemaining () {
          return Math.max(0, 50 - (Date.now() - start))
        }
      }
      return window.setTimeout(function () {
        cb(idleDeadline)
      }, 1)
    }
  }
})
```

Which is the preferred approach?

**Comment by danielroe** [comment]
@Mini-ghost The first approach seems better to me 👍

**Review by danielroe — APPROVED** [review]
Thank you! Looks good to me but @pi0 may have some more ideas for improvement.

**Review by pi0 — APPROVED** [review]

**Comment by pi0** [comment]
Thank you so much for helping on this feature @Mini-ghost <3

I've made few more reactors to the PR to simplify do small fixes and also integrated with new payload prerendering using `link:prefetch` hook to be ready to land.

**Pull request merged**
