### PR TITLE
docs: change app-config url to avoid naming conflicts with app.vue

### PR DESCRIPTION
**Pull request by clemcode**
### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
`app.config` and `app` URLs were conflicting in the `directory structure` section causing a blank page. Renaming to app-config for URLs.

### CODE REVIEW

**Review by Atinux — APPROVED** [review]

**Comment by pi0** [comment]
Is it something we might track for content/docus and fix later to support dot in content paths? /cc @farnabaz

**Comment by Atinux** [comment]
I think it has to be directly with content since this theme does not use Docus.

Also, we need to improve the Docs Aside to fix the highlight @clemcode (but in another release of the website-theme)

**Comment by Atinux** [comment]
Merging since it fixes a broken page for now.

**Comment by manniL** [comment]
Please do not forget to set up redirects, even if temporary!

**Pull request merged**
