### PR TITLE
docs: add `theme-color` meta

### PR DESCRIPTION
**Pull request by sanjaiyan-dev**
Hi, By adding `<meta name="theme-color " />` we can customise the colour of the app bar. For more info please [click here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color)

I have added #00db80 as a theme-colour  :)

_Extremely sorry if I made any mistakes :(_

### CODE REVIEW

**Review by pi0 — APPROVED** [review]

**Comment by pi0** [comment]
Thanks! Looks good to me also in mobile. FYI we are replacing docs soon with a Nuxt 3 theme. We probably need to include it there.

**Comment by sanjaiyan-dev** [comment]
> Thanks! Looks good to me also in mobile. FYI we are replacing docs soon with a Nuxt 3 theme. We probably need to include it there.

Yh sure 🙌💪

Can you please give additional information about it please

**Comment by pi0** [comment]
This is the PR if you like to follow: #5479

**Comment by sanjaiyan-dev** [comment]
> This is the PR if you like to follow: #5479

Thanks a lot

**Pull request merged**
