### PR TITLE
docs: update documentation for configs

### PR DESCRIPTION
**Pull request by P4sca1**
### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

It was not clear to me, how to change the runtime config via env variables at runtime.
I also added the composition API methods for accessing the config.

I don't know if the same replacing logic applies to `privateRuntimeConfig`. If that's the case, it would be good to add an explanation there too. Also, it might be good to mention that current env values are compiled into the script during build time when using `apiKey: process.env.API_KEY` and are not overwritten during runtime when setting `API_KEY`. Instead one has to set `apiKey`.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by danielroe** [comment]
Many thanks for this! The logic applies to the privateRuntimeConfig as well. Here's the source:

https://github.com/nuxt/framework/blob/d07d572263b45108e2a98a9924bf0d8dcba902fa/packages/nitro/src/runtime/app/config.ts#L8-L12

**Comment by P4sca1** [comment]
@danielroe I have updated the information about `privateRuntimeConfig` and updated the example.
Also, I decided to remove the information about the Nuxt payload, because I feel like it leads to more confusion and the new information about runtime replacement is sufficient.

By the way, thank you for your great talk at Vue.js Nation yesterday, I really enjoyed it. Keep up the good work 👏

**Review by danielroe — COMMENTED** [review]
only a small typo - otherwise looks good to go 🚀

**Review by danielroe — APPROVED** [review]

**Comment by pi0** [comment]
Thanks!

**Pull request merged**
