### PR TITLE
docs(examples): add examples to docs

### PR DESCRIPTION
**Pull request by clemcode**
### 🔗 Linked issue

#715

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR introduces a new "Examples" top-level entry in the docs nav, and display every example with a CSB / Stackblitz sandbox and short introduction.

Preview: https://deploy-preview-3966--nuxt3-docs.netlify.app/examples/

### CODE REVIEW

**Comment by pi0** [comment]
Checking [preview](https://deploy-preview-3966--nuxt3-docs.netlify.app/examples/), it is a really nice improvement to the docs!!

Some suggestions regarding categories:

- `composables` are not components! We can have both of them under either `Features`, `Auto Imports`, or their own category 
- `module-extend` can be under `advanced` section 
- `wasm` can be under `section`
- `reactivity transform` can be under `experimental` section
- `Seo` is not really a valid term for meta tags at least at the moment, we could categorize them under a `composables` section together with all other composable examples/

**Naming suggestions:**

We don't need `With ` in titles. Initially, it was to indicate examples that represent a nuxt feature. I'm happy to drop it also from names of examples

**Included examples:**

`hello-world` is at least missing. Why is that?

**Tips within Layout **

This is troublesome to maintain almost same description twice and making example less readable. I would merge tips from code and move to markdown.

Also now that we have a **wrapper**, this is less need to show such wrapper unless directly opening example in non-embed mode.

**Comment by clemcode** [comment]
Thanks for the review @pi0 , fully agree on that, I'll make the changes!

**Comment by clemcode** [comment]
To delete the `with` prefixes, I'll wait that we all agree on the PR and commit just before merging, as it will break the preview since we pull the examples from the `main`, where they still contain the prefix:

```
::sandbox{repo="nuxt/framework" branch="main" dir="examples/with-composables" file="app.vue"}
```

**Comment by Atinux** [comment]
Looks great and we can iterate later on 👏 

You can remove the `with` prefix

**Comment by Atinux** [comment]
Seems the CI is not happy about the changes, do you mind checking it @pi0 ?

**Comment by pi0** [comment]
Sure! We need to only update lockfile when renaming examples or adding new one.

BTW really nice work!

**Review by pi0 — APPROVED** [review]

**Pull request merged**
