### PR TITLE
fix(bridge): add modules with hooks after all other modules

### PR DESCRIPTION
**Pull request by danielroe**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

It is otherwise impossible for modules to add their own auto imports or configure vite on a Bridge install.

### CODE REVIEW

**Comment by Rigo-m** [comment]
Is this a possible fix to this? https://github.com/nuxt-community/storybook/issues/359

**Review by pi0 — APPROVED** [review]
LGTM. We might introduce some flags to `installModule` later to make it easier :D

**Comment by ThomasBerne** [comment]
The seems to be still present in the 4.2.0 version. Has it been released ?

**Comment by ThomasBerne** [comment]
I checked the changes made to @nuxt/bridge and this [error](https://github.com/nuxt-community/storybook/issues/351) seems to occur even with the changes @danielroe did. Can we fix this ?

**Comment by danielroe** [comment]
@ThomasBerne Would you raise a new issue? I don't believe the issued linked above was intended to be resolved by this PR.

**Pull request merged**
