### PR TITLE
docs: increment directory structure numbers

### PR DESCRIPTION
**Pull request by 516310460**
### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by 516310460** [comment]
Index duplication

**Comment by 516310460** [comment]
image
0 or 1 ?

**Comment by pi0** [comment]
Thanks.

**Comment by 516310460** [comment]
> Thanks.

:)

**Comment by 516310460** [comment]
> image
> 
> 0 or 1 ? And
> image
> 
> Is the document rigorous?

Look at this

**Comment by 516310460** [comment]
Got it

**Pull request merged**
