### PR TITLE
docs: use nuxt 3 and website theme

### PR DESCRIPTION
**Pull request by Tahul**
### ❓ Type of change

- [X] 👌 Enhancement (improving an existing functionality like performance)

### 📚 Description

Upgrade `docs/` directory to use latest nuxtlabs/docus version.

This implies that the docs now runs on Nuxt 3.

TODO:

- [x] Re-add Algolia DocSearch
- [x] Global review with @pi0 @danielroe @clemcode @Atinux

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [X] I have updated the documentation accordingly.

resolves https://github.com/nuxt/framework/issues/3951

### CODE REVIEW

**Comment by pi0** [comment]
This is amazing! Thank you so much for working on this.

Same as previous PR, I think we shall move new docs to the theme so that can maintain it easier and also reuse for the translations repo. I think this way we can finally move forward from legacy nuxt 2 docs.

**Comment by Tahul** [comment]
I would love to get some help to get the deployment to work 😄

**Comment by Tahul** [comment]
@pi0 ; I updated the PR following your guidelines!

nuxt/nuxt3-docs now holds the theme for `nuxt/framework/docs`. 🙂

It is used via `@docus/nuxt3-docs` package but can be republished under the naming that fits you!

Will continue the work on Docus tomorrow closing the TODOs from here!

**Comment by Tahul** [comment]
@pi0 @danielroe ; this one is ready to be merged for me! (if that latest deployment passes 😄)

@Atinux @alexchopin might want to make a last review!

**Review by danielroe — COMMENTED** [review]
This looks great! ❤️

**Comment by Atinux** [comment]
recording

We need to fix these layout shifts issues on the icons top right and I feel something weird when changing layouts.


<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 102.0.5005.115 on Mac OS 10.15.7
Viewport:  1728 x 1000 @2x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-5479--nuxt3-docs.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=102.0&resolution=1728x1000&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-5479--nuxt3-docs.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=62acbd7b511c070008556556&commentID=62afa9466fa84c244058443b&resolution=resolved)

**Comment by danielroe** [comment]
I think the icon layout shift is due to how color mode icon is implemented - it flickers to three dots and back:

CleanShot 2022-06-20 at 09 36 42

cc: @Tahul

**Comment by Atinux** [comment]
It should not flicker on client-side :thinking:

**Comment by Tahul** [comment]
> It should not flicker on client-side 🤔

https://github.com/nuxtlabs/docus/commit/7ecc8e871803926c9c60af3227b97e9b301c4012

This is fixed in that commit.

**Comment by Tahul** [comment]
Just updated the PR, it now uses:
- RC.5
- Latest Docus (@nuxt-themes/docus)
- @nuxt/content v2.1 (edge release)

CleanShot 2022-07-14 at 06 25 15@2x

I think it is ready for another review @danielroe @pi0 😄

**Comment by pi0** [comment]
We tracked `'./style.59211af6.js'` issue to `@nuxtjs/algolia`. Disabling it from theme layer fixes have to still check what is wrong.

**Comment by Tahul** [comment]
(@danielroe @pi0 ; I fixed the PR.. I think it might still need additional reviews from @Atinux @alexchopin ?)

**Comment by pi0** [comment]
Rebased and resolved merge conflicts. Seems we have new regressions form content or theme layer can you please check @Tahul @Atinux ? 🙏🏼 

- /Users/pooya/Code/framework/docs/node_modules/@nuxt-themes/docus/components/prose/ProseThead.vue?vue&type=style&index=0&scoped=0885f9bc&lang.postcss:3:3: The u-border-gray-200 class does not exist. If u-border-gray-200 is a custom class, make sure it is defined within a @layer directive.
- / route shows 404

**Comment by Atinux** [comment]
Once merged, we will need to update the deployments to point v3.nuxtjs.org to Vercel one.

**Review by Atinux — APPROVED** [review]

**Pull request merged**
