### PR TITLE
fix(nuxt3): change entry to use asynchronous import

### PR DESCRIPTION
**Pull request by phoenix-ru**
### 🔗 Linked issue

#1444

[Discussion](https://github.com/nuxt/framework/discussions/870)

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Async boundary in the client is crucial for supporting Webpack 5 Module Federation. With this PR and an [example repository](https://github.com/phoenix-ru/nuxt3-module-federation-example), Module Federation will be officially supported by Nuxt 3!

Q: Is it a breaking change?
A: The contract for the entry does not change. Webpack 5 build does function as intended. **Vite build also works.**

I am also intending on publishing a Nuxt module for an easy configuration in the projects.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly. Documentation does not need to be updated, this is an internal change which doesn't face users.

### CODE REVIEW

**Comment by phoenix-ru** [comment]
**Help is needed with testing.**

The generated code is guaranteed to run in Webpack 5.
However, I couldn't perform local testing using `yarn run test` due to weird issues in bridge. Attaching them below
```
nuxt3\packages\bridge\src\runtime\asyncData.ts
  1:0  error  Parsing error: Declaration or statement expected

nuxt3\packages\bridge\src\runtime\cookie.ts
  1:0  error  Parsing error: Declaration or statement expected

nuxt3\packages\bridge\src\runtime\fetch.ts
  1:0  error  Parsing error: Declaration or statement expected
```

**Comment by phoenix-ru** [comment]
One confirmed issue with my implementation is that when trying `npx yarn play`, it fails to resolve `./bootstrap.mjs` (because it's not transpiled yet). Source: https://github.com/nuxt/framework/pull/2223/files#diff-1ea713a781c67ef6463c3558bcaaba5401852cce08177bbc81bf63960fb09086R5

However, when doing `import('./bootstrap')`, it fails during build time (because the module is now transpiled and Node can't dynamically assume `.mjs`).
I am looking into fix

**Comment by phoenix-ru** [comment]
@danielroe Do you know what's the status of this PR?

**Review by pi0 — APPROVED** [review]

**Comment by pi0** [comment]
So sorry for the late merge @phoenix-ru. Refactor in this PR and also your experimental repo seems amazing 💚

**Pull request merged**
