### PR TITLE
Improve loading sequence of hydration `<script />` 🚀

### PR DESCRIPTION
**Pull request by sanjaiyan-dev**
### Improve loading sequence of hydration `<script />` 🚀

>This will help us to improve-: 
>- Improvements in FCP, LCP metric, faster time to visual-completeness.
>- Reduced developer cost for curating the loading sequence for FCP, LCP.
>- Additional optimization and predictability given the guaranteed order of execution of defer scripts.

References -:

1.  Next js current implementation -: https://github.com/vercel/next.js/discussions/24938
2. About script loading -: https://gist.github.com/jakub-g/385ee6b41085303a53ad92c7c8afd7a6

### CODE REVIEW

**Comment by danielroe** [comment]
At the moment we are preloading the script in the head, and then adding it at the end of the document. That is important for hydration, as we can't hydrate the DOM before the DOM is present.

Perhaps you could open an issue with some issues to address, and we could discuss it there?

**Comment by sanjaiyan-dev** [comment]
> At the moment we are preloading the script in the head, and then adding it at the end of the document. That is important for hydration, as we can't hydrate the DOM before the DOM is present.
> 
> Perhaps you could open an issue with some issues to address, and we could discuss it there?

Sorry, actually here script is fetched parallel with html parsing (same as `<link rel="preload" />`) but for browser which doesn't support `<link rel="preload" />`.

Defer attribute and `type="module"` behave same as adding script to bottom but parallel to html parsing :)

**Comment by sanjaiyan-dev** [comment]
> > At the moment we are preloading the script in the head, and then adding it at the end of the document. That is important for hydration, as we can't hydrate the DOM before the DOM is present.
> > Perhaps you could open an issue with some issues to address, and we could discuss it there?
> 
> Sorry, actually here script is fetched parallel with html parsing (same as `<link rel="preload" />`) but for browsers which doesn't support `<link rel="preload" />`.
> 
> Defer attribute and `type="module"` behave same as adding script to bottom but fetches scripts parallel to html parsing :)

For ref-: 

https://web.dev/efficiently-load-third-party-javascript/#defer

https://v8.dev/_img/modules/async-defer.svg

**Comment by sanjaiyan-dev** [comment]
> > At the moment we are preloading the script in the head, and then adding it at the end of the document. That is important for hydration, as we can't hydrate the DOM before the DOM is present.
> > Perhaps you could open an issue with some issues to address, and we could discuss it there?
> 
> Sorry, actually here script is fetched parallel with html parsing (same as `<link rel="preload" />`) but for browsers which doesn't support `<link rel="preload" />`.
> 
> Defer attribute and `type="module"` behave same as adding script to bottom but fetches scripts parallel to html parsing :)

@danielroe For ref-: 

https://web.dev/efficiently-load-third-party-javascript/#defer

https://v8.dev/_img/modules/async-defer.svg

**Comment by danielroe** [comment]
I'm familiar with what async/defer do.

We have a hard dependency in Nuxt 3 on [browsers that support Proxy](https://caniuse.com/proxy) as this is a requirement for Vue 3.

To implement something like this we would need to make some more changes to rendering, not completely omit all preload/prefetches, as this PR does.

I'm very receptive to anything that will improve Nuxt performance, and appreciate your time in raising this PR.

However, would you instead open a separate issue and explain a bit more about the benefit this will bring? (Ideally with benchmarks.) Is it mostly about increasing support for browsers that don't support preload?

We can then discuss how it might implemented.

**Comment by sanjaiyan-dev** [comment]
> I'm familiar with what async/defer do.
> 
> We have a hard dependency in Nuxt 3 on [browsers that support Proxy](https://caniuse.com/proxy) as this is a requirement for Vue 3.
> 
> To implement something like this we would need to make some more changes to rendering, not completely omit all preload/prefetches, as this PR does.
> 
> I'm very receptive to anything that will improve Nuxt performance, and appreciate your time in raising this PR.
> 
> However, would you instead open a separate issue and explain a bit more about the benefit this will bring? (Ideally with benchmarks.) Is it mostly about increasing support for browsers that don't support preload?
> 
> We can then discuss how it might implemented.

https://github.com/nuxt/framework/issues/7939

**Pull request closed without merging**
