### PR TITLE
docs: add note about transpiling node_modules

### PR DESCRIPTION
**Pull request by richardeschloss**
### 🔗 Linked issue
#2542 

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

I added one sentence that I think is very useful and could have saved me a bit of time in troubleshooting the "cannot resolve #app" issue. I think this may become a frequent issue, and in case people are not checking Nuxt's github repo, they may find their solution in the docs. 

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Review by danielroe — COMMENTED** [review]
I think this is a good thing to mention in the docs, and appreciate you creating the PR! ❤️  I think it should probably be in the (upcoming) 'Module authors' page rather than the ESM concepts page, however.

**Comment by richardeschloss** [comment]
Just to clarify, would it be in a new "Module authors" section, or would it be in this existing one: https://v3.nuxtjs.org/concepts/esm#library-author-guide ?

**Comment by pi0** [comment]
@richardeschloss New section soon ;)

**Comment by pi0** [comment]
Closing this PR for now since nuxt module dirs are automatically added to transpile which is the case for this.

**Pull request closed without merging**
