### PR TITLE
feat(nuxt)!: only scan top level  `composables/` and support glob

### PR DESCRIPTION
**Pull request by antfu**
### 🔗 Linked issue

https://github.com/unjs/unimport/pull/86#issuecomment-1178724831

Unimport upgraded from 0.4.x to 0.6.x in https://github.com/nuxt/framework/pull/6032

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [x] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR changes auto-imports' behavior to exclude nested folders from auto-imports. 

To get auto imports for nested modules, you can re-export them from `composables/index.ts` (see alternative below)

```js
// composables/index.ts
export { usebar } from './utils/bar.ts'
```

### 👉 Migration

⚠️ Breaking change: `composables/*/index.ts` is no longer being scanned and you need to reexport. In order to preserve previous behavior, please configure `autoImports.dirs`:

```ts [nuxt.config.ts]
export default defineConfig({
  // ...
  autoImports: {
    dirs: [
      'composables', // top-level modules
      'composables/*/index.{ts,js,mjs,mts}' // one level directories's index.js,
      //'composables/**', // Scan all nested directories
    ]
  }
})
```

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by danielroe — APPROVED** [review]
Looks good to me.

**Comment by pi0** [comment]
Seems a good defaults change to simplify scanning with top level only. Can you please:

- Update PR description for breaking change and migration guide (to link from release notes)
- Split the nested composables example from simple one to the end of docs page
- Suggest `composables/index.ts` for reexports
- Swap two options for nested to prefer top-level file over configuration

**Comment by danielroe** [comment]
Updated migration guide whilst @pi0 was reviewing. One thought: we should also update logic for other scanned directories, likely in same PR to reduce breaking change.

**Comment by pi0** [comment]
But surely we need to make scanned directories to a closer behavior. Let's keep changes splitted. @danielroe What other dirs are you thinking?

**Comment by danielroe** [comment]
Plugins currently have this `/index` behaviour. Middleware and layouts are also scanned at a single level with no way to configure it. (Which might be okay, but see also https://github.com/nuxt/framework/pull/5842.)

**Comment by pi0** [comment]
Strict behavior of middleware/layouts makes sense. We can add option later without breaking changes. (breaking) Change for plugins makes sense with same next release 👍🏼

**Comment by pi0** [comment]
PR description: I would suggest to add top level `index.ts` reexport (convention over configuration) as recommended migration path.

**Comment by antfu** [comment]
Migration guide updated. Let me know if you have any other suggestion, or update it directly :)

**Review by pi0 — APPROVED** [review]

**Comment by pi0** [comment]
(upgraded mistakenly merged via previous #6032 PR). Latest edge release contains the changes via merge commit of this.

**Pull request merged**
