### PR TITLE
docs: fix pnpm run dev command

### PR DESCRIPTION
**Pull request by BlackdestinyXX**
### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

The pnpm command for run an app in development mode (pnpm run dev -- -o) doesn't work.
Error: 
```
Unknown option: 'o'
For help, run: pnpm help run

```

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [x ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Atinux** [comment]
Would love to get your input on this @antfu

**Comment by antfu** [comment]
`pnpm run dev -- -o` work fine for me (`pnpm@6.11.0`) and I think the docs were correct. 

@BlackdestinyXX Did you mistype it as `pnpm run dev -o`? Or what's your `dev` script bound to?

**Comment by pi0** [comment]
Thanks for the PR @BlackdestinyXX but this is the way to pass extra arguments to pnpm commands and it works fine:

(linux)
image

(windows)
image


It might be because you are missing `--` (`pnpm run dev -o` is wrong) or using an older version of pnpm.

**Comment by BlackdestinyXX** [comment]
Oh ok, thank you, the next time I'll open a issue instead of a PR.

**Pull request closed without merging**
