### PR TITLE
docs: fix more redirect issues

### PR DESCRIPTION
**Pull request by danielroe**
### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Various issues of pages being renamed.

For future reference, `scripts/crawl.mjs` is what I use to identify these issues.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by Atinux — APPROVED** [review]

**Comment by Atinux** [comment]
Thank you @danielroe !

I believed we had a GH action to automate this right?

**Comment by danielroe** [comment]
There is an action, but it's triggered on GitHub deployment status updates, which Netlify doesn't seem to use for some reason.

**Comment by Atinux** [comment]
I guess when using to Vercel that will work

**Comment by danielroe** [comment]
Yes, it does.

**Pull request merged**
