### PR TITLE
docs: add Stackblitz links for examples

### PR DESCRIPTION
**Pull request by antfu**
### 🔗 Linked issue

In the future we could also have some meta info for each example in a JSON file, with a short descriptions and pointers to docs

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by pi0** [comment]
Love it! Thanks!

**Comment by pi0** [comment]
Some comments:
- We need to fix lint issue (probably also with auto-update script)
- We probably don't need to maintain a `.stackblitzrc` file and reduce boilerplate
  - `installDependencies` can be part of `startCommand`
  - `startCommand` can be embedded as `?command` query string
- Maybe making a symlink from docs to also display table somewhere? (~> #1960)

**Comment by antfu** [comment]
> startCommand can be embedded as ?command query string

That sounds like a good idea. But it does not seem to work and I didn't find it documented anywhere either, did I missed anything?

**Comment by pi0** [comment]
My fault! Query is `terminal=`. Example:

- https://stackblitz.com/github/nuxt/framework/tree/main/examples/use-cookie?terminal=dev

**Comment by antfu** [comment]
Where did you learn that magic? 🤣

Updated

**Review by pi0 — APPROVED** [review]

**Pull request merged**
