### PR TITLE
fix: sanitize import filenames in generated imports

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

#2192

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

We should consider whether we want to support the use case in the linked issue, although the PR is safe to merge and likely a good idea.

**Note**: `vite` and `rollup` themselves are not yet compatible with resolved ids containing `'` so even with this PR, the original issue is not solved.

- [x] https://github.com/rollup/rollup/pull/4262
- [ ] https://github.com/vitejs/vite/pull/5896

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.
- [x] ~~pending https://github.com/unjs/paneer/pull/2~~

### CODE REVIEW

**Comment by pi0** [comment]
This seems nice initiative and refactors anyway even until rollup is not supporting 👍 But I guess we should move this fix to mlly for generation utils and refactor once.

**Comment by pi0** [comment]
@danielroe Would you please help resolving merge conflicts?

**Comment by danielroe** [comment]
Current status is we are creating a new library in `unjs` namespace to host these utils.

I suggest I wait to resolve merge conflicts until we have that repo created or a PR open in it.

**Comment by danielroe** [comment]
@pi0 It would be good to get this merged in even if we still have upstream issues with vite to resolve. (Unless you think there's something else we should fix here?)

**Review by pi0 — APPROVED** [review]

**Pull request merged**
