### PR TITLE
docs: update sitemap

### PR DESCRIPTION
**Pull request by clemcode**
### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR introduces a new sitemap for the documentation website:

- Getting Started (quick start, tutorial, migration)
- Guides (concepts, features, deployment...)
- References (directory structure, components, composables, API reference...)
- Examples
- Community

Preview: https://deploy-preview-4063--nuxt3-docs.netlify.app/

### CODE REVIEW

**Comment by pi0** [comment]
@clemcode Thanks! Do you mind also fixing merge conflicts?

**Comment by pi0** [comment]
Some early reviews:

- First, amazing changes!
- It would be nice to fill-in-the-blank sections. We can use a short description + linking to most relevant page (guide/module => reference/advanced guide/plugin=>reference/plugin, tuturial => examples/hello-world, etc) stating currently work on progress
- We need to redirect at least for https://v3.nuxtjs.org/concepts/esm since is referenced in many places so far
- In order to both simplify and make consitancy with [vuejs docs](https://vuejs.org/guide/introduction.html), i would use `Guide` (instead of `guides`) and `references` to `Reference` or `API`
- Let's not introduce planned but not yet to be documented parts such as Theming

By moving some parts from References to Guide, we can make references part really a reference and use of guides for detailed writing:

- Moving directory/structure from References to `guide`  considering it is introduction to what is what not an API reference
- Moving more of advanced section from References to `guide` > `Going further`. It is already half-way merged with module author guide (BTW love this new name!)
  - With Exception of "Lifecycle hooks" which are reference still
- Moving commands section to Guide > CLI
- Server section of reference can be removed we already have Features/Server and if is to be extended, we can introduce Guides > Server

- Regarding ordering in references, i would suggest this:
  - Composables
  - Components
  - Utils (replacing global api. they are utils and auto impoorted)
  - Hooks

**Comment by Atinux** [comment]
> It would be nice to fill-in-the-blank sections. We can use a short description + linking to most relevant page (guide/module => reference/advanced guide/plugin=>reference/plugin, tuturial => examples/hello-world, etc) stating currently work on progress
> We need to redirect at least for [v3.nuxtjs.org/concepts/esm](https://v3.nuxtjs.org/concepts/esm) since is referenced in many places so far

This is planned 😊 

> In order to both simplify and make consistency with [vuejs docs](https://vuejs.org/guide/introduction.html), I would use Guide (instead of guides) and references to Reference or API

Agree, updated to `Guide` and `API` (`/api-reference`)

> Let's not introduce planned but not yet to be documented parts such as Theming (and I would also remove Tutorial, even if is going to be added tomorrow! Docs feel more WIP when we use it as todo list with empty sections)

I believe this is the best case to finalise these parts, more than happy to work on this with the people who worked on it!

**Comment by Atinux** [comment]
> Moving directory/structure from References to guide considering it is an introduction to what is what, not an API reference

Not sure about this yet in **its current state**, it might be refactored as page since most of its current content is empty anyway before being moved to `Guide`.

Also, we have to see about the `nuxt.config` file which is actually an API reference

> Moving more of the advanced section from References to guide > Going further. It is already halfway merged with the module author guide (BTW love this new name!)

For `Nuxt Internals` I agree, Nuxt Kit is not a guide by looking at it but an API reference

> Moving commands section to Guide > CLI

I disagree on this, the CLI will be explained in the getting started and tutorial and it is not directly a feature for making Nuxt app from my POV

> Server section of reference can be removed we already have Features/Server and if is to be extended, we can introduce Guide > Server

The idea behind this is to show all the utils we have in `h3` to write for the server part, I think it can be updated for sure before moving forward, will look at it tomorrow.

> Regarding ordering references, I would suggest this [...]

Updated to at least have composables, components and utils (even though Vue call it "Global API" for `defineComponent`)

**Comment by pi0** [comment]
> Not sure about this yet in its current state, it might be refactored as page since most of its current content is empty anyway before being moved to Guide.

But also it is definitely not a reference. Maybe moving to guide in collapsed state?

Regarding config, it makes sense to be in reference. We can link to reference>config from directory structure (if have any)

With this refactor, we can also rethink about improving API section design to be searchable and more accessible.

> For Nuxt Internals I agree, Nuxt Kit is not a guide by looking at it but an API reference

Makes sense. Let's keep kit utils inside API :) 

> I disagree on this, the CLI will be explained in the getting started and tutorial and it is not directly a feature for making Nuxt app from my POV

Well, guides are not exactly tutorials. They already include detailed instructions. CLI in current state _looks like api_ while it should be really a more user-friendly guide and also in the future, more explaining about DX of devtools in almost same place for me. 

> The idea behind this is to show all the utils we have in h3 to write for the server part, I think it can be updated for sure before moving forward, will look at it tomorrow.

Certainly for APIs exposed and auto-installed by Nitro. They shall remain in API. Yet we definitely also need a guides section regarding server part. Introducing directory structure and usage. It can be as minimal as a features page in guides for me for now. 

> even though Vue call it "Global API" for defineComponent

Hmm I don't mind about keeping it as Global API either. Only I think for vue makes sense since it is a single library and they are vue's global API exports. Nuxt is not exactly a library with single Global API but has utils.

**Review by danielroe — COMMENTED** [review]
I love it! ❤️

Some comments:

- [ ] the 'Get started' buttons on home page 404s
- [ ] the 'Learn more about Nitro' button on home page 404s
- [ ] on [this page](https://deploy-preview-4063--nuxt3-docs.netlify.app/migration/overview) a number of the navigation items all produce 404s

**Review by Atinux — APPROVED** [review]
Happy to merge and move forward, amazing work done @clemcode @pi0 ❤️

**Pull request merged**
