### PR TITLE
chore: update examples to `^3.0.0-rc.10` and use global `defineNuxtConfig`

### PR DESCRIPTION
**Pull request by pi0**
### 🔗 Linked issue

#https://github.com/nuxt/framework/pull/7497

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by darthf1** [comment]
Is it possible to keep the imports somewhere, but with a comment it can be omitted in case of auto import? 

It's my understanding now auto imports can be disabled, having the import path visible is still useful. But please correct me if Im wrong.

**Comment by pi0** [comment]
> It's my understanding now auto imports can be disabled, having the import path visible is still useful. But please correct me if Im wrong.

Feature to disable auto imports is related to runtime bundler. We always have `defineNuxtConfig` available (check linked PR)

**Comment by darthf1** [comment]
> > It's my understanding now auto imports can be disabled, having the import path visible is still useful. But please correct me if Im wrong.
> 
> Feature to disable auto imports is related to runtime bundler. We always have `defineNuxtConfig` available (check linked PR). But of course you can choose to explicitly import from `'nuxt/config'`

Ah ok! Thanks for the clarification. 

Since this PR is to remove all the references to this import from the docs (since it can be auto imported), how is a user (who prefers manual imports) going to know / learn what the import path is? Is it possible to keep one reference somewhere in the docs?

**Comment by pi0** [comment]
Added explicit docs. Nice suggestion 👍🏼

**Review by Atinux — APPROVED** [review]

**Comment by darthf1** [comment]
> Added explicit docs. Nice suggestion 👍🏼 

Awesome. Thank you for making the changes.

**Pull request merged**
