### PR TITLE
fix(bridge): normalize strings in vite middleware template

### LINKED ISSUE #2221: Replace of 'undefined' in router middleware
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.11.0`
- Nuxt Version:     `2.16.0-27299536.ab1c6cb4`
- Package Manager:  `yarn@1.22.10`
- Bundler:          `Webpack`
- User Config:      `ssr`, `components`, `devtools`, `sourcemap`, `productionTip`, `telemetry`, `modern`, `bridge`, `publicRuntimeConfig`, `privateRuntimeConfig`, `head`, `manifest`, `pwa`, `loading`, `plugins`, `modules`, `buildModules`, `buildDir`, `router`, `styleResources`, `css`, `vite`, `axios`, `io`, `auth`, `dateFns`, `fontawesome`, `toast`, `sentry`, `stripe`, `render`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`, `@nuxtjs/pwa@3.3.5`, `@nuxtjs/auth-next@5.0.0-1637745161.ea53f98`, `@nuxtjs/sentry@5.1.6`, `@nuxtjs/toast@3.3.1`, `nuxt-stripejs@1.1.6`, `portal-vue/nuxt`, `v-wave/nuxt`
- Build Modules:    `@nuxtjs/date-fns@1.5.0`, `@nuxtjs/fontawesome@1.1.2`, `@nuxtjs/style-resources@1.2.1`, `@nuxt/postcss8@1.1.3`, `@nuxt/bridge@3.0.0-27296423.f3082ca`
------------------------------

### Reproduction

Add the following to `nuxt.config.js`:

```js
router: {
    base: '/',
    middleware: ['auth'],
    linkActiveClass: 'active',
    linkExactActiveClass: 'exact-active',
    extendRoutes(routes) {
      routes.push({
        path: '/',
        redirect: '/write',
      })
    }
  },
```

The important part that fails is `middleware: ['auth']` as specified in the `@nuxtjs/auth-next` module docs as well as in the Nuxt docs.

Try to start the dev server.

### Describe the bug

When running `yarn dev` the following error appears:

image

This is bc in `node_modules/@nuxt/bridge/dist/chunks/module2.mjs`:

image

at `map((m) => ...)` where `m` is simply the string `"auth"` and therefore `m.src` is undefined.

I raised this error already in the `@nuxt/auth` repo [here](https://github.com/nuxt-community/auth-module/issues/1323#issuecomment-980787536), but they think it is a Nuxt Bridge problem and I agree, bc it shows up when following the Nuxt docs.

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #2221

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR normalises strings in router middleware for the purposes of `middleware.js` template (for example, from `@nuxtjs/auth`).

Note that this doesn't entirely fix issue in reproduction in original issue as there are some issues in `@nuxtjs/axios` that will need to be handled upstream.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by pi0** [comment]
More modules are using `string` input. Shall we, instead of ignoring, converting to `{ src }` and add to template?

**Comment by toniengelhardt** [comment]
@pi0 would be great to solve the problem for all modules

**Comment by danielroe** [comment]
@pi0 Hm. Maybe we need to solve in `@nuxtjs/auth` in that case?

The issue is that this is how the 'auth' middleware is defined:
https://github.com/nuxt-community/auth-module/blob/dev/templates/plugin.js#L7

In other words, we don't have a specific source file to point to.

**Comment by pi0** [comment]
Nuxt 2 middleware as plain string are supported in Nuxt 2 and also with Bridge on webpack. Silently ignoring them for vite is not a solution.

BTW Auth module is not even compatible yet with the bridge also not sure to understand the issue with plugin middleware injection...

**Review by pi0 — APPROVED** [review]

**Comment by bmulholland** [comment]
Are there any docs on what auth would need to do to be compatible?

**Pull request merged**
