### PR TITLE
fix(nuxt): allow cookies to be set to `null` to unset them

### PR DESCRIPTION
**Pull request by danielroe**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

remake of https://github.com/nuxt/framework/pull/8754

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by pi0 — APPROVED** [review]

**Comment by Aareksio** [comment]
@danielroe This caused `useCookie<Type[]>('name', { default: () => [] })` to be `Ref<Type[] | null>` which forces us to write null checks while in reality the type is strictly never `null`.

**Comment by danielroe** [comment]
@Aareksio I appreciate it; the issue is that it can be null if you set it to null. You could cast it `as Ref<Type[]>` in your case.

**Comment by Aareksio** [comment]
After this change, all code must be explicitly null-checked or `as`-patched. 
I would argue that neither of the following is good DX:

```ts
const languages = useCookie<string[]>('languages', { default: () => ['en'] }) as Ref<string[]>
// or
for (const language of (languages as Ref<string[]>).value) {}
```

**Comment by danielroe** [comment]
I wonder if we could allow overriding with generic - so by default it infers a type with null, but you can override by setting your own value? And if you need to delete you can add `| null` to the generic type?

**Comment by Aareksio** [comment]
Before the change, you should be able to do `useCookie<string | null>()` and the type would be `Ref<string | null>`. Rather painless opt-in.

**Pull request merged**
