### PR TITLE
refactor: update unjs dependencies to stable v1

### PR DESCRIPTION
**Pull request by pi0**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Update uns packages with semver major to v1.

Also updating nitropack temporarily to edge channel to finish update in one step.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by manniL** [comment]
@pi0 Could you briefly explain why was `ohmyfetch` renamed to `ofetch`? I'm a little afraid people have to memorize "yet another library name" after getting used to `ohmyfetch` + using the package in projects 🙈

**Comment by pi0** [comment]
> Could you briefly explain why was ohmyfetch renamed to ofetch? 

it is a shorter name. I initially wanted to release as shorter name but took long to get publish access to it. As for Nuxt users, interface name is still `$fetch`. Perhaps can add some references to ofetch readme to explain renaming.

**Comment by manniL** [comment]
> it is a shorter name

Do you think the shorter name really worth all the migration for all packages using `ohmyfetch` now explicitly?

**Comment by pi0** [comment]
Hmm will probably keep `ohmyfetch` as placeholder in a semver-major. Making it easier to migrate other packages. But for renaming really had to do this before v3 as you notice, it gets harder to break API or make renames as we have more users.

**Comment by manniL** [comment]
> Hmm will probably keep `ohmyfetch` as placeholder in a semver-major. 

That'd be good at least 👍 

> But for renaming really had to do this before v3

Or not at all 🙈

**Pull request merged**
