### PR TITLE
docs: add full stop in `<LinkExample>`

### PR DESCRIPTION
**Pull request by UzzolX**
### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by max-programming** [comment]
How is that a typo anyway 🤔

**Comment by UzzolX** [comment]
Look at the other components. They have a dot (.) at the end. For example, ReadMore.vue components. But LinkExample.vue was missing one.
https://github.com/UzzolX/Screenshot/blob/master/nuxt3-samll-typo.PNG

**Review by danielroe — APPROVED** [review]

**Comment by pi0** [comment]
Thanks!

**Comment by max-programming** [comment]
> Look at the other components. They have a dot (.) at the end. For example, ReadMore.vue components. But LinkExample.vue was missing one.
> https://github.com/UzzolX/Screenshot/blob/master/nuxt3-samll-typo.PNG

Oh okay got it. I thought this was a spam PR like the ones that come in Hacktoberfest.

Sorry about that

**Pull request merged**
