### PR TITLE
fix(nuxt): normalize manifest css file entries 

### PR DESCRIPTION
**Pull request by ThomasRalee**
### ❓ Type of change
- [ ] 📖 Documentation (updates to the documentation or readme)
- [X] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
Update mapping logic on clientManifest files to segregate `.css` files from `.js` files.

### 📝 Checklist
- [X] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### Reproduction
- Stackblitz reproduction [link](https://stackblitz.com/edit/github-a9hkn9-qphw3c?file=nuxt.config.ts,package.json,tsconfig.json), CSS is not loaded properly.
- Command to reproduce: `yarn generate && yarn preview`
image

### CODE REVIEW

**Comment by pi0** [comment]
Thanks for the PR @ThomasRalee. Would you please revert your changes to package.json and playground and provide a reproduction? the linked issue seems not relevant.

**Comment by ThomasRalee** [comment]
Hi @pi0, thanks for the fast reply!

I've reverted the changes to `package.json` and `playground`, not sure how to create a reproduction. Would you mind sharing some tips on that?

**Comment by pi0** [comment]
You can fork [this sandbox](https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz?file=README.md) to add broken usecase that this pull request tries to fix. When provided, it would be nice to also include it to basic fixture (https://github.com/nuxt/framework/tree/main/test/fixtures/basic) to avoid future regressions with it.

**Comment by ThomasRalee** [comment]
Hi @pi0,

Thanks for the tips! I've created a reproduction link [here](https://stackblitz.com/edit/github-a9hkn9-qphw3c?file=nuxt.config.ts,package.json,tsconfig.json), and also added a simple fixture to check that CSS stylesheet link tag is added to head tags.

**Comment by ThomasRalee** [comment]
@pi0,

I am getting errors trying to run the `webpack` and `dev` fixtures on my local, to resolve this 😞 :
- `test:fixtures:dev`
image

- `test:fixtures:webpack`
image

**Comment by pi0** [comment]
I can locally test on fixture and confirm it works. Building in test environment has strange behavior currently that no scripts are injected at all! Because of that, marked your new test as todo.

**Review by pi0 — APPROVED** [review]

**Pull request merged**
