### PR TITLE
fix(nuxt): page hydration and double load

### LINKED ISSUE #6592: Page component is created twice when navigating to it from page which uses different layout
### Environment

- Operating System: `Linux`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@8.14.0`
- Builder:          `vite`
- User Config:      `modules`, `css`, `vite`, `runtimeConfig`, `build`
- Runtime Modules:  `@formkit/nuxt@1.0.0-beta.10`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-nodp3z?file=pages/page.vue

There are two pages and each of them uses a different layout. Just click on link to another page, then click on link to index page. You can see in console that index page component is created and mounted twice.

### Describe the bug

If you are navigating using NuxtLink to another page which uses different layout, that page component is created twice.

### Additional context

It started happening after upgrade from rc6 to rc7. Still happening on rc8.

I also noticed that await useAsyncData on rc6 does not block navigation when navigating to page with another layout. Layout shows without page, then after page data is loaded, page is mounted. This does not happen on rc7 and rc8, navigation is correctly blocked until data is fetched. Maybe it has something to do with this.

### Logs

_No response_

### LINKED ISSUE #7337: nuxtApp.isHydrating is always false in page setup script when using async page
### Environment

Nuxi 3.0.0-rc.9
RootDir: /home/projects/github-gagmal-zapxnv
Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.1`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-gagmal-zapxnv?file=pages/index.vue

Open `/sync`, `/a`, `/b/b1`, `/c/c1`
Watch the client console to see if the app is hydrated or not.

### Describe the bug

The nuxtApp.isHydrating becomes false before async page component is resolved.
And it also affect all nested page of the async page (no matter it is async or not).

### Additional context

I am writing an app. And I want to get fresh data without the initial request.

To achieve that. I am writing it like

```js
const a = await useFetch('url', () => {
  initialCache: !!process.server || nuxtApp.isHydrating
})
```

so it will only try to actually fetch the data if it isn't initial load.
But it turns out it always say the page is hydrated if I am using async page.
Which is completely unexpected.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by mmis1000**
### 🔗 Linked issue
Fix #7337, fixes #6592, closes https://github.com/nuxt/framework/pull/7400

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR is a remake of #7400

Besides of fix and workaround in #7400.

1. This PR use a different approach to handle hydrating, so change of page wrapper isn't required.
2. This PR ensure that layout and any page wrapper never change outside of the window that route navigation happens.
    - so #6592 should never happen again
3. This PR adds proper test for linked issue
    - so regression after this should be noticed

A remaining issue is temporary blank page when switching between layout and navigate at the same time.
But that isn't fixable without vuejs/core#6736.
So it isn't handled here.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by danielroe — APPROVED** [review]
This looks great to me - thank you so much 😊

I've made a couple of minor changes and one fix (to ensure this works for layouts that are children of `<NuxtPage>`); let me know if you spot any issues.

**Comment by mmis1000** [comment]
> This looks great to me - thank you so much 😊
> 
> I've made a couple of minor changes and one fix (to ensure this works for layouts that are children of `<NuxtPage>`); let me know if you spot any issues.
> 
> P.S. really appreciate the work on the tests...

Looks fine to me except I am wondering what is this for https://github.com/nuxt/framework/pull/7940/commits/21d872ca3f1b51da7fa2787551db2d85acce24e6#diff-ef9ac7f796e2b5d9a4a232b098d7ce5dd92610191d35dfaf10612a76bfe532ddR50

Is this exist to ensure that layout used inside page changes when writing things like `useRoute().meta.layout = xxx` inside a page component? 

Also, this didn't seem to change any test results, is there a test for it?

**Comment by danielroe** [comment]
Yes, so, for example of you are changing page which has a layout within it, it doesn't force rerender the existing page with the new layout before suspense resolves. And yes, we should add a test for that case. I'll do that later unless you get to it first.

**Comment by mmis1000** [comment]
> Yes, so, for example if you are changing page which has a layout within it, it doesn't force rerender the existing page with the new layout before suspense resolves. And yes, we should add a test for that case. I'll do that later unless you get to it first.

Yea, I think it would makes more sense in anthoer PR instead of this due to following reason.

1. That isn't actually part of this change set
2. You can't test this without alternative app.vue. It need a another fixture of app because the default app.vue defaults to have a layout in it. 
    - To test this, the change set would be too big for this PR.

**Comment by danielroe** [comment]
I have great sympathy for your desire to push it to another PR, but I think it's not as complex as you are worried it will be.

It's just a matter of creating two files:

`~/pages/internal-layout.vue` and `~/pages/internal-layout/[slug].vue`. We can turn off normal layouts in `internal-layout.vue` with `definePageMeta({ layout: false })` and take full control by adding our custom `<NuxtLayout>` inline in the page.

I do think it would be good to add tests for this in this PR as it would be good to check that https://github.com/nuxt/framework/pull/7940/commits/21d872ca3f1b51da7fa2787551db2d85acce24e6 is doing what it's meant to do, and that we don't accidentally regress the fix.

**Comment by mmis1000** [comment]
> I have great sympathy for your desire to push it to another PR, but I think it's not as complex as you are worried it will be.
> 
> It's just a matter of creating two files:
> 
> `~/pages/internal-layout.vue` and `~/pages/internal-layout/[slug].vue`. We can turn off normal layouts in `internal-layout.vue` with `definePageMeta({ layout: false })` and take full control by adding our custom `<NuxtLayout>` inline in the page.
> 
> I do think it would be good to add tests for this in this PR as it would be good to check that [21d872c](https://github.com/nuxt/framework/commit/21d872ca3f1b51da7fa2787551db2d85acce24e6) is doing what it's meant to do, and that we don't accidentally regress the fix.

https://stackblitz.com/edit/github-42bhq4?file=layouts%2Ftest3.vue,pages%2Findex.vue

I think it will still also change the outer layout even you already set `layout: false`. So you need a App.vue without outer layout to test it.

**Comment by tada5hi** [comment]
would love to see this pr merged :see_no_evil:

**Comment by danielroe** [comment]
The only thing it needs is the test I mentioned previously. I'm on it.

**Comment by tada5hi** [comment]
any news on this ?

**Review by danielroe — APPROVED** [review]
Looks good to me

**Review by Atinux — APPROVED** [review]

**Comment by Atinux** [comment]
Thank you very much!

It would be nice to have a way to detect how much kb add pull requests to the Nuxt default bundle size.

**Comment by loilo** [comment]
So, just out of curiosity (because I ran into #6592 as well) – when is the next RC scheduled to be available? 🥹

**Comment by danielroe** [comment]
Until then, you can try this out in the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/).

**Comment by loilo** [comment]
Thank you, will take a look. 🥳

**Pull request merged**
