### PR TITLE
test: add key matching test for keyed composables

### PR DESCRIPTION
**Pull request by danielroe**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Adds some extra tests to protect against https://github.com/nuxt/framework/issues/6178. See also https://github.com/nuxt/framework/pull/6191.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by pi0 — APPROVED** [review]

**Comment by pi0** [comment]
(windows test seems failing. retrying CI)

**Comment by danielroe** [comment]
Checking on a Windows system to see if it's revealed an actual issue.

**Comment by danielroe** [comment]
Just to update: this _seems_ a strange Vue core bug - the mismatch is actually between `\r` on client and `\r\n` on server. 🤦

**Comment by danielroe** [comment]
~> https://github.com/vuejs/core/issues/6410

**Comment by mercs600** [comment]
@danielroe vue fixed this bug, can we upgrade vue dependency ?

**Comment by danielroe** [comment]
You don't need Nuxt to update to benefit from a new Vue release. Just upgrade it with `npm upgrade vue` or your package manager's equivalent.

We use a caret for this reason. https://github.com/nuxt/framework/blob/main/packages/nuxt/package.json#L75

**Comment by mercs600** [comment]
Thats right, I have done it, thank you

**Pull request merged**
