### PR TITLE
feat(nuxt): nested layout files

### PR DESCRIPTION
**Pull request by DannyAndres**
This PR resolves the issue [#5793](https://github.com/nuxt/framework/issues/5793). A developer will be able to create multiple folders in /layouts and then access them in pages.

This feature was heavily inspired in the PR [Adds support for folders in /layouts #1865
](https://github.com/nuxt/nuxt.js/pull/1865) for Nuxt 2 and works in the exact same way.

For instance, if in /layouts there are 2 folders like:

- layouts
  - folder1
  - folder2

the developer is able to create files which are named the same but they are in different folders.
Like folder1/default.vue and folder2/default.vue and then access those layouts in /pages using following rule.

`folder_in_layouts` + `layout-file-name`

### CODE REVIEW

**Comment by DannyAndres** [comment]
In advance sorry for the extra edition, was done by `npx yarn lint --fix`

**Review by danielroe — CHANGES_REQUESTED** [review]
Nice idea! If you get a chance, would you please revert the spacing/formatting changes to help us as we review this?

**Comment by DannyAndres** [comment]
Sure, I will send another commit directly from main and manually lint the corresponding files

**Comment by jjjrmy** [comment]
bump, really interested in this feature

**Pull request closed without merging**
