### PR TITLE
fix(bridge): fixed reactivity on csr of useState reactive payload

### LINKED ISSUE #2133: useState is not reactive
### Environment

Any nuxt2 + bridge environment

### Reproduction
[codesandbox](https://codesandbox.io/s/reproduction-2134-rhk4b)

### Describe the bug

`useState` creates a new `nuxtApp.payload.useState` entry automatically via `toRef`, but it's not reactive (computed and watch methods doesn't trigger). Fixable via the `set` composable.

### Additional context

Related to https://github.com/vuejs/composition-api/issues/855

### Logs

_No response_

### PR DESCRIPTION
**Pull request by Rigo-m**
### 🔗 Linked issue
#2133

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Resolves #2133 

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by danielroe — APPROVED** [review]
Thanks ❤️

**Comment by Rigo-m** [comment]
This should fix it as well https://github.com/vuejs/composition-api/pull/859.
If you can merge it in bridge, I will take care of undoing the pr once @antfu has pushed a new composition api version.

**Comment by pi0** [comment]
Thanks @Rigo-m!

**Comment by reegodev** [comment]
Thank you guys for the quick merge

**Pull request merged**
