### PR TITLE
fix(nuxt): process middleware after plugins

### LINKED ISSUE #4703: Route in plugin is always /
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.1`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-trznob?file=plugins/plugin.ts

### Describe the bug

Hi,

I am trying to get the current path in a plugin using `useRoute()` but it always returns the route with the path `/`.

```
export default defineNuxtPlugin((nuxt) => {
    const route = useRoute()
    console.log(route.path) // always '/'
})
```

My workaround is to use the `app:created` hook in the plugin and call `useRoute()` outside the hook and access the path inside the hook:

```
export default defineNuxtPlugin((nuxt) => {
    const route = useRoute()
    nuxt.hook('app:created', () => {
        console.log(route.path) // works
    })
})
```

If I call `useRoute()` inside the hook I get a nuxt `instance unavailable error`:

```
export default defineNuxtPlugin((nuxt) => {
    nuxt.hook('app:created', () => {
        const route = useRoute() // error
        console.log(route.path)
    })
})
```

Shouldn't the nuxt instance be available inside `app:created` hook?
My goal is to call an API on init in a nuxt module based on the current path. Is there another recommended way to do this?

Best regards
David

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/framework/issues/4257, see also https://github.com/nuxt/framework/issues/4259, resolves #4703

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR changes middleware behaviour to defer processing middleware until after plugins are initialised. This means that middleware will have access to plugin injections, and that plugins have the chance to add middleware themselves.

~In addition (and this is the breaking change), it skips processing middleware on client-side for server-side-rendered routes, aligning with Nuxt 2.~

**Potential for future improvement** - `.client` middleware that _does_ run on client-side but not on server

**SSR**:
1. set up router + current route (by pushing it)
2. add middleware
2. process plugins
3. replace current route with itself, triggering middleware

**CSR**:
1. set up router + await ready
2. add middleware
3. process plugins
3. replace current route with itself, triggering middleware

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Atinux** [comment]
Beautiful work @danielroe ❤️ 

How can we add a test case to confirm the behaviour and avoid any potential regression in the future?

**Comment by Atinux** [comment]
Happy to merge anyway and test internally 😊

**Comment by pi0** [comment]
I'm wondering if we can keep client/server behavior consistent by either executing middleware on initial render or not. If server-only middleware on initial is desired, it can be easily guarded with `if (process.server )`

**Comment by Atinux** [comment]
I am not sure about this, I believe middleware shall only be run once. This is the behavior I have done in Nuxt 2 on purpose.

What is the advantage of rerunning them on client-side?

**Comment by pi0** [comment]
> I believe middleware shall only be run once. 

They are. Like anything else during hydration and same as plugins, they run once on the server and once on the client side.

In general, I don't think there is any advantage that we are even calling middleware on initial rendering. It is a really strange use case that could be easily replicated with a nuxt plugin already and removed all this complexity for pushing route and ordering... But if we are doing this, it should be consistent IMO. We already introduced this change on Nuxt 3 and breaking it once again doesn't makes sense.

**Comment by danielroe** [comment]
At the moment, this PR simply fixes a couple of bugs; it doesn't change the current behaviour, which runs middleware on client _and_ server. It's not meant to make a decision on the question of whether to run middleware on initial client-side load. Let's have that conversation in https://github.com/nuxt/framework/issues/4259; we can always follow up with a further PR reverting [`e14384e` (#4645)](https://github.com/nuxt/framework/pull/4645/commits/e14384e15698bd56768265d42038063d084f7171).

(We could also support  `.client` and `.server` suffixes for middleware and it would be good to have only one breaking change rather than two in a row.)

**Review by pi0 — APPROVED** [review]

**Comment by vis97c** [comment]
Why does a "global" middleware run only on the server. If people think they only need it on the server just use a process.server conditional. I have a usecase to run it twice but it seems like it is not possible with the current implementation. @pi0 What a re your thoughts on this?

**Comment by danielroe** [comment]
Please see my immediately preceding comment above. This PR did not end up changing the fact that middleware runs on both client and server.

See https://github.com/nuxt/framework/issues/4259 for an issue requesting this to change and run only once.

**Pull request merged**
