### PR TITLE
feat: add dev-only component

### LINKED ISSUE #7949: Add `DevOnly` component
### Describe the feature

A component to render it slot only during dev would be useful in some cases.

The content should be tree shaken during build

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

### PR DESCRIPTION
**Pull request by stafyniaksacha**
### 🔗 Linked issue

resolves #7949

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Introduce `<DevOnly>` component that render its content only in development mode.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by danielroe** [comment]
What about instead tree-shaking out the component + its children from the final build, so it really leaves no trace?

**Comment by stafyniaksacha** [comment]
We can add a custom core unplugin like the [`/src/core/plugins/tree-shake.ts`](https://github.com/nuxt/framework/blob/main/packages/nuxt/src/core/plugins/tree-shake.ts) ? 

And remove everything that match `<DevOnly>(:?[\s\S]*)*<\/DevOnly>` from sources during build ?

What do you think @danielroe ?

**Comment by danielroe** [comment]
Exactly. Might possibly be within the same plugin.

**Comment by stafyniaksacha** [comment]
I created another plugin since the tree-shake runs on vue script and js/ts files

**Comment by Tahul** [comment]
Hey!

Can't wait to have this merged, this will be so useful to enhance DX on themes :)

**Review by pi0 — APPROVED** [review]
LGTM. Although tree-shaking should happen in SFCs, if we are outside and not happening, the chunk will silently be included but not rendered/loaded.

**Pull request merged**
