### PR TITLE
docs: disable transitions by default

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

hotfix to work around #8414 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

I do not believe we are currently using transitions so we probably should disable these anyway. This also serves to seriously reduce a memory leak that we're looking into.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by pi0 — APPROVED** [review]
LGTM. /cc @Atinux

**Comment by Atinux** [comment]
Thanks @danielroe 

Shall we simply disable transitions by default in Nuxt 3? 🤔

**Comment by danielroe** [comment]
There is merit in that. They cause issues like https://github.com/nuxt/framework/issues/3587 when many users may not be using them at all ...

wdyt @pi0?

**Comment by Atinux** [comment]
It also brings Nuxt 3 as light as possible when starting

**Comment by pi0** [comment]
Makese sense to disable transitions by default. We only need proper way to guide users to enable it back

**Comment by manniL** [comment]
I think disabling them by default is a good idea to reduce friction, as long as docs cover how to use them (e.g. with an extra section).

**Pull request merged**
