### PR TITLE
docs: update doc meta

### PR DESCRIPTION
**Pull request by f3ltron**
### 🔗 Linked issue

close https://github.com/nuxt/framework/issues/1647

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Improve meta documentation with an example.

@danielroe I think I may have an error with style;

Screen Shot 2021-11-08 at 10 00 54 PM

Screen Shot 2021-11-08 at 10 01 34 PM

I am using the hello-world example.

```js
import { defineNuxtConfig } from 'nuxt3'

export default defineNuxtConfig({
  meta: {
    meta: [
      {
        name: 'viewport',
        content: 'test content'
      }
    ],
    script: [{ src: 'https://awesome-lib.js' }],
    style: ['background-color: red;'],
    link: [{ href: 'awesome-lib.css', rel: 'stylesheet' }]
  }
})

```

When I use the array of object it add attributes to style as expected

If you confirm that's an error I can work on it.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by danielroe** [comment]
I'm not sure if I've missed your commits (as I only see a lockfile change), but [this](https://github.com/nuxt/framework/discussions/1080#discussioncomment-1482694) is how you add a `<style>` tag with content.

**Comment by f3ltron** [comment]
Oh true. I thought I pushed it... Hum Ok will check ^^.

May be worth to have the doc even it is going to change will add it

**Comment by f3ltron** [comment]
Now its good ! thanks @pi0  @danielroe  for the help

**Review by danielroe — APPROVED** [review]

**Comment by pi0** [comment]
Thanks 💚

**Pull request merged**
