### PR TITLE
feat(nuxt): make `useFetch` options reactive

### LINKED ISSUE #5993: `useFetch` does not account for params change
### Environment

Nuxt CLI v3.0.0-rc.6                                                                                              16:22:47
RootDir: *                                  16:22:47
Nuxt project info:                                                                                                16:22:47

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`, `build`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.0`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-brbcqx?file=pages/index.vue

### Describe the bug

When we use useFetch with the same URL, but with different query string parameters, changing the parameters does not trigger a new fetch. As you can see in the repo, navigating from Page One to Page Two, and back, does trigger the composable `useData`, but the data is not fetch given new params. If you navigate to `/` or `/page2` directly, then we can see the correct data.

Additionally, using the querystring directly in the URL also results in the same bug.

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #5993

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This allows passing refs/computed properties as fetch options (e.g. for a param value), and automatically refetching when these values change.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by pi0 — APPROVED** [review]

**Comment by JorenSynaeveTM** [comment]
Hi Daniel. I don't know where to respond, so I'm posting my question here. I'm having issues getting this to work. I have the following code in my page: 
```
...
const page = computed(() => {
  return parseInt(useRoute().query.page) || 1;
});

/* This part worked with the pagination as expected
const { pending, data } = useAsyncData(
  "test",
  () =>
    $fetch(
      `${useRuntimeConfig().public.API_BASE_URL}/api/productlist?page=${
        page.value
      }&includeUser=true`,
      {
        headers: {
          Authorization: `Bearer ${useCookie("apiToken").value}`,
        },
      }
    ),
  {
    watch: [page],
  }
);
*/

/* This part does not work */
const { pending, data } = myAsyncData(
  "test",
  `/api/productlist?page=${page.value}&includeUser=true`,
  {},
  {
    watch: [page],
  }
);

...
```

When trying to extract this logic to a custom composable for better error handling and adding a bearer token, it stopped working. Here is my custom composable:

```
import { AsyncDataOptions, UseFetchOptions } from "nuxt/dist/app/composables";

export const myAsyncData = (key: string, url: string, fetchOptions?: UseFetchOptions<unknown>, asyncDataOptions?: AsyncDataOptions<unknown>) => {
    const config = useRuntimeConfig();

    return useAsyncData(key, () =>
        $fetch(
            config.public.API_BASE_URL + url,
            {
                ...fetchOptions,
                async onRequest({ request, options }) {
                    const token = useCookie("apiToken");

                    if (token.value) {
                        options.headers = {
                            ...options.headers,
                            Authorization: `Bearer ${token.value}`,
                        };
                    }

                    console.log("[fetch request]");
                }
            }
        ),
        {
            ...asyncDataOptions
        });
};

```

Could you please take a look on why this is not working?
Ps: If I have to move this comment somewhere else, please tell me to do so.

**Comment by danielroe** [comment]
yes, this is probably not the right place. if you have a follow-up question, would you open a discussion instead?

you should instead do something like this:

```js
const { pending, data } = await useAsyncData(
  'test',
  '/api/productlist',
  {
    params: {
      page,
      includeUser: true
    }
  }
)
```

... and that should work, automatically watching `page`. You can pass `params` though and it should also work with `myAsyncData`.

**Comment by yashika** [comment]
awesome!

**Comment by Developer27149** [comment]
Thanks bro

**Pull request merged**
