### PR TITLE
v3.1.0 [draft]

### PR DESCRIPTION
**Pull request by pi0**
> **3.1.0** is the first minor release after [Nuxt 3.0](https://github.com/nuxt/framework/releases/tag/v3.0.0) including bug fixes and enhancements and is expected in Jan 2023.

This is an early draft for tracking changes and expected additions.

Please refer to the [Edge Channel Docs](https://nuxt.com/docs/guide/going-further/edge-channel) if you want to try the changes ahead of time. 

## 👀 Highlights

- Lots of improvements to the documentation and website after release (you can already see them in [nuxt.com](https://nuxt.com))
- Migrated to [Vite 4](https://vitejs.dev/blog/announcing-vite4.html) and [Rollup 3](https://github.com/rollup/rollup/blob/master/CHANGELOG.md#300).
- Experimental component Islands and [server only components](https://nuxt.com/docs/guide/directory-structure/components#server-components)
- Nitropack v2 with Rollup 3 support (Upcoming)

Expected from roadmap:

- [x] ~~Server-only components~~: https://github.com/nuxt/framework/pull/9972
- [ ] ~~Unit testing with vitest within Nuxt env~~ ~> https://github.com/danielroe/vitest-environment-nuxt
- [ ] ~~New examples section~~ (@Atinux @danielroe  - probably delay)
- [ ] Autoinstall support for extends with git repositories (@pi0 - probably delay)
- [ ] Try adding experimental config schema to the core (https://github.com/nuxt-experiments/nuxt-config-schema)
- [ ] Nitropack v2 release (@pi0)

### 🚀 Enhancements

  - **nuxt:** Experimental server component islands ([#5689](https://github.com/nuxt/framework/pull/5689))
  - **nuxt:** Add `onNuxtReady` composable ([#9478](https://github.com/nuxt/framework/pull/9478))
  - `useNuxtData` composable ([#9262](https://github.com/nuxt/framework/pull/9262))
  - **nuxt:** Support for extending `error.vue` in layers ([#9521](https://github.com/nuxt/framework/pull/9521))
  - **vite:** Upgrade to vite 4 ([#9238](https://github.com/nuxt/framework/pull/9238))

### 🩹 Fixes

  - Remove `postcss.config` from the schema ([#9181](https://github.com/nuxt/framework/pull/9181))
  - **nuxt:** Include missing `<NuxtPage>` component props ([#9204](https://github.com/nuxt/framework/pull/9204))
  - **nuxt:** Allow layouts to receive custom props ([#9395](https://github.com/nuxt/framework/pull/9395))
  - **test-utils:** Do not hide vitest output ([#9442](https://github.com/nuxt/framework/pull/9442))
  - **nuxt:** `useCookie` with defaults should return non-null value ([#9449](https://github.com/nuxt/framework/pull/9449))
  - **nuxt:** Defer render-blocking prefetches until after load ([#9475](https://github.com/nuxt/framework/pull/9475))
  - **nuxt:** Speculation rules should be reactive ([#9472](https://github.com/nuxt/framework/pull/9472))
  - **kit:** Support applying `.nuxtignore` within external layers ([#9599](https://github.com/nuxt/framework/pull/9599))
  - **nuxt:** Remove deprecated `req`/`res` access ([#9636](https://github.com/nuxt/framework/pull/9636))
  - **nuxt:** Await plugin asyncData promises in nuxt hook ([#9616](https://github.com/nuxt/framework/pull/9616))
  - **schema:** Add hookable dependency ([#9648](https://github.com/nuxt/framework/pull/9648))
  - **vite:** Skip _only_ vite transform middleware ([#9602](https://github.com/nuxt/framework/pull/9602))
  - **nuxt:** Remove absolute paths from routes objects ([#9655](https://github.com/nuxt/framework/pull/9655))
  - **nuxt:** Make `<dev-only>` regexp less greedy ([#9679](https://github.com/nuxt/framework/pull/9679))

### 💅 Refactors

  - **nuxt:** Fix typo in internal plugin names ([#9201](https://github.com/nuxt/framework/pull/9201))
  - **nuxt:** Use `pathe.join` for layer lookup ([#9540](https://github.com/nuxt/framework/pull/9540))
  - Split out type imports from value imports ([#9225](https://github.com/nuxt/framework/pull/9225))
  - **nuxt:** Remove `vue-meta` for head support ([#9638](https://github.com/nuxt/framework/pull/9638))
  - **nuxt:** Remove unused support for auto imports with globalThis injection ([#9630](https://github.com/nuxt/framework/pull/9630))

### 📖 Documentation

  - Fix paths to migration guides ([#9071](https://github.com/nuxt/framework/pull/9071))
  - Fix broken paths ([#9076](https://github.com/nuxt/framework/pull/9076))
  - Set nuxt stability to stable ([#9075](https://github.com/nuxt/framework/pull/9075))
  - Fix broken link ([24c8653b](https://github.com/nuxt/framework/commit/24c8653b))
  - Update redirects ([f01fc186](https://github.com/nuxt/framework/commit/f01fc186))
  - **seo:** Add robots file ([#9111](https://github.com/nuxt/framework/pull/9111))
  - Improve images quality ([#9112](https://github.com/nuxt/framework/pull/9112))
  - Fix broken links in examples ([#9119](https://github.com/nuxt/framework/pull/9119))
  - Update Vercel icon to support dark mode ([a4768fd5](https://github.com/nuxt/framework/commit/a4768fd5))
  - Update website-theme version ([16117060](https://github.com/nuxt/framework/commit/16117060))
  - Fix typo in `commands/add` ([#9206](https://github.com/nuxt/framework/pull/9206))
  - Remove stable release warning regarding options api ([#9186](https://github.com/nuxt/framework/pull/9186))
  - **jobs:** Remove unused asset ([#9116](https://github.com/nuxt/framework/pull/9116))
  - Fix typos in modules section ([#9227](https://github.com/nuxt/framework/pull/9227))
  - Updated info about `404.vue` ([#9155](https://github.com/nuxt/framework/pull/9155))
  - External configuration table ([#9189](https://github.com/nuxt/framework/pull/9189))
  - **homepage:** Optimize gem textures ([#9234](https://github.com/nuxt/framework/pull/9234))
  - Add space between sentences ([#9207](https://github.com/nuxt/framework/pull/9207))
  - Improve seo titleTemplate and add social images ([#9235](https://github.com/nuxt/framework/pull/9235))
  - Update link to mdc extension ([#9251](https://github.com/nuxt/framework/pull/9251))
  - Add missing space ([#9276](https://github.com/nuxt/framework/pull/9276))
  - **partners:** Add brain agency partner ([#9277](https://github.com/nuxt/framework/pull/9277))
  - Add warning about `.client` and `onMounted` hook ([#9263](https://github.com/nuxt/framework/pull/9263))
  - Use `layout` in the example of `definePageMeta` ([#9322](https://github.com/nuxt/framework/pull/9322))
  - **schema:** Add example and description for `imports.dirs` ([#9346](https://github.com/nuxt/framework/pull/9346))
  - Change app-config URL to avoid naming conflicts with `app.vue` ([#9377](https://github.com/nuxt/framework/pull/9377))
  - Add redirect for `app.config` to `app-config` ([66efcd59](https://github.com/nuxt/framework/commit/66efcd59))
  - **installation:** Add button to nuxt.new ([7c998982](https://github.com/nuxt/framework/commit/7c998982))
  - **installation:** Typo in sentence ([53d5a5a5](https://github.com/nuxt/framework/commit/53d5a5a5))
  - **roadmap:** Add i18n module to the roadmap ([#9403](https://github.com/nuxt/framework/pull/9403))
  - Add more social cards ([a50855ba](https://github.com/nuxt/framework/commit/a50855ba))
  - **seo:** Add sitemap url to robots.txt ([#9309](https://github.com/nuxt/framework/pull/9309))
  - **introduction:** Add hero and cards ([#9334](https://github.com/nuxt/framework/pull/9334))
  - Disable markdownlint on mdc file ([#9428](https://github.com/nuxt/framework/pull/9428))
  - **homepage:** Fix typo ([#9426](https://github.com/nuxt/framework/pull/9426))
  - Add Project name placeholder ([#9421](https://github.com/nuxt/framework/pull/9421))
  - Update announcements to add stable release ([a73a75c3](https://github.com/nuxt/framework/commit/a73a75c3))
  - Update playwright url ([#9483](https://github.com/nuxt/framework/pull/9483))
  - Make `vite` monospace too ([#9490](https://github.com/nuxt/framework/pull/9490))
  - Update agencies expertises ([d36d1155](https://github.com/nuxt/framework/commit/d36d1155))
  - Add nuxt layers introduction and authoring guide ([#9405](https://github.com/nuxt/framework/pull/9405))
  - Heading and formatting improvements for layers ([c307ee8b](https://github.com/nuxt/framework/commit/c307ee8b))
  - Update website-theme ([cf4e7bf3](https://github.com/nuxt/framework/commit/cf4e7bf3))
  - Update internal links to the bridge overview page ([228bc9ce](https://github.com/nuxt/framework/commit/228bc9ce))
  - Recommend to install non-edge version of `@nuxt/test-utils` ([#9543](https://github.com/nuxt/framework/pull/9543))
  - Compress social image to jpg and upgrade website-theme ([770cdf90](https://github.com/nuxt/framework/commit/770cdf90))
  - **agencies:** Add liip ([#9552](https://github.com/nuxt/framework/pull/9552))
  - Fix typo and update theme ([d500ac4e](https://github.com/nuxt/framework/commit/d500ac4e))
  - Update theme version ([5fdb7b6f](https://github.com/nuxt/framework/commit/5fdb7b6f))
  - **rendering:** Hide light image in dark mode ([#9620](https://github.com/nuxt/framework/pull/9620))
  - Update examples link ([#9152](https://github.com/nuxt/framework/pull/9152))
  - Add docs for `preloadRouteComponents` ([#9607](https://github.com/nuxt/framework/pull/9607))
  - Add missing line breaks ([#9671](https://github.com/nuxt/framework/pull/9671))
  - Indicate `navigateTo` options are optional ([#9672](https://github.com/nuxt/framework/pull/9672))
  - Add community page ([#9519](https://github.com/nuxt/framework/pull/9519))
  - **community:** Fix client-side images display ([#9704](https://github.com/nuxt/framework/pull/9704))
  - **community:** Temporary disable newsletter subscription ([#9740](https://github.com/nuxt/framework/pull/9740))
  - **concepts:** Add `utils/` to  directory-based auto-imports ([#9739](https://github.com/nuxt/framework/pull/9739))

### 🎨 Styles

  - Split out type imports ([6d0c4910](https://github.com/nuxt/framework/commit/6d0c4910))

### CODE REVIEW

**Comment by Celibioux** [comment]
no pnpm support without the shamefully-hoist ? ( just checking )

**Comment by productdevbook** [comment]
"nuxt": "npm:nuxt3@latest",


image

**Comment by daniluk4000** [comment]
> no pnpm support without the shamefully-hoist ? ( just checking )

Hold on, this is not working even in Nuxt 3 without shamefully hoist?

**Comment by pi0** [comment]
@Celibioux @daniluk4000 Please followup https://github.com/nuxt/framework/issues/5411 for pnpm support. It is not fully working yet without flag.

@productdevbook Would you please open an issue to reproduce the bug? 🙏🏼

**Comment by danielroe** [comment]
moved ~> https://github.com/nuxt/nuxt/pull/18406

**Pull request closed without merging**
