### PR TITLE
fix(schema): disallow setting vite server properties

### PR DESCRIPTION
**Pull request by manniL**
### 🔗 Linked issue

https://github.com/nuxt/framework/issues/7316#issuecomment-1239235095

### ❓ Type of change

- [x] 👌 Enhancement (improving an existing functionality like performance)

### 📚 Description

Disallows setting the port via `vite.server.port` in the `nuxt.config.ts`.
@pi0 Any other options we should disallow? Or `vite.server` in general?

### 📝 Checklist

- [x] I have linked an issue or discussion.

### CODE REVIEW

**Comment by pi0** [comment]
> @pi0 Any other options we should disallow? Or vite.server in general?

I think makes sense to server `vite.server` to never too 👍🏼 (quickly) checking code we are not using it at all.

**Review by pi0 — APPROVED** [review]

**Comment by tobiasdiez** [comment]
Setting `server` no `never` now leads to ts errors for hmr configs that are sometimes necessary (e.g. for gitpod):
```ts
vite: {
    server: {
      hmr: ...
    }
}
```
But `hmr` is not exposed by the top-level `server` config. What is the correct config with rc.10?

**Comment by pi0** [comment]
@tobiasdiez Can you please open a PR to limit never to only port/host options? Configuring vite.server.hmr is valid.

**Comment by manniL** [comment]
> @tobiasdiez Can you please open a PR to limit never to only port/host options? Configuring vite.server.hmr is valid.

Will fix this ☺️

**Pull request merged**
